id: AC2438265
base_file: f4598.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:56:25.094495
  last_modified_at: 2022-05-31 06:56:25.094503
