id: AC2438265
base_file: fE720.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:56:25.096958
  last_modified_at: 2022-05-31 06:56:25.096962
